name: streamlink-FFMPEG7

on:
  workflow_dispatch:
    inputs:
      ffmpegcom:
        description: 'Command ffmpeg'
        required: true

jobs:
  live-streaming:
    runs-on: ubuntu-latest

    steps:
      - name: install streamlink
        run: sudo pip3 install streamlink
      - name: install ffmpeg
        run: sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg7 -y > /dev/null;sudo apt update -qq > /dev/null;sudo apt install ffmpeg -y -qq > /dev/null
      - name: live stream
        run: ${{ github.event.inputs.ffmpegcom }}
