name: streamlink

on:
  workflow_dispatch:
    inputs:
      ffmpegcom:
        description: 'Command ffmpeg'
        required: true

jobs:
  live-streaming:
    runs-on: ubuntu-latest

    steps:
      - name: install streamlink
        run: sudo pip3 install streamlink
      - name: run command
        shell: bash
        run: ${{ github.event.inputs.ffmpegcom }}
